[package]
org = "wso2"
name = "order_lifecycle"
version = "0.1.0"
distribution = "2201.12.7"

[[dependency]]
org = "ballerinax"
name = "paypal.orders"
version = "2.0.0"
repository = "local"

[build-options]
observabilityIncluded = true
